#
# Dockerfile_dynamic_analysis to build "Android Analyzer Service" container images
#
FROM ubuntu:16.04

MAINTAINER Markus Gabriel e1326657@student.tuwien.ac.at

# Installing required linux packages
# * python 2 (for app)
# * mysql client
# * libssl-dev for uwsgi websocket handshake
RUN apt-get update && apt-get install -y \
    python-pip \
    python-mysqldb \
    libssl-dev \
    && apt-get clean

# Downloading and installing python dependencies of app
RUN pip2 install --upgrade pip && pip2 install \
	flask Flask-Uploads Flask-Session Flask-Sqlalchemy subprocess32 enum34 Flask-login bcrypt flask-socketio \
	uwsgi gevent \
	Flask-Testing \
	celery

ADD webapp/. .
ADD common common
# Setting locale, to prevent errors with special characters
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Android analyzer app
ENTRYPOINT ["uwsgi", "--http", "0.0.0.0:5000", "--gevent", "10", "--http-websockets", "--master", "--wsgi-file", "wsgi.py"]
