#
# Dockerfile to build a static analysis task container image for the "Android Analyzer Service"
#
FROM ubuntu:16.04

MAINTAINER Markus Gabriel e1326657@student.tuwien.ac.at

# Installing required linux packages
# * tools used in setup
# * python 2 (for app)
# * mysql client
# * dependencies for androguard
RUN apt-get update && apt-get install -y \
    wget \
	python-pip \
	python-mysqldb \
	openjdk-8-jdk openjdk-8-source libssl-dev libffi-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev g++ \
	&& apt-get clean

# Downloading and installing apktool
RUN wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
RUN wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.1.jar
RUN mv apktool_2.2.1.jar apktool.jar
RUN chmod a+x apktool.jar apktool

# Downloading and installing python dependencies of app
ADD static_analysis/requirements.txt .
RUN pip2 install -r requirements.txt

# Get python code
ADD static_analysis/. .
ADD common common

# Setting locale, to prevent errors with special characters
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENTRYPOINT celery worker -A src.task.celery -Q static_queue --loglevel=info -Ofair --concurrency=1 -n static@%h --without-gossip