version: '2'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"

  dynamic_analysis:
    build:
      context: dynamic_analysis
      dockerfile: Dockerfile
      args:
        - API_VERSIONS=19,25
        # Set the API versions that should be supported
        # more versions may enable more specific analysis, but will significantly increase docker build time
        # make sure that API_VERSIONS in environment are the same
    links:
      - rabbit
    depends_on:
      - rabbit
      - files
    volumes:
      - files:/files
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
      - API_VERSIONS=19,25
      # make sure that API_VERSIONS fit the ones specified in build args

  static_analysis:
    build:
      context: static_analysis
      dockerfile: Dockerfile
    links:
      - rabbit
    depends_on:
      - rabbit
      - files
    volumes:
      - files:/files

  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    links:
      - rabbit
    depends_on:
      - rabbit
      - files
    ports:
      - "5000:5000"
    volumes:
      - files:/files

  files:
    build:
      context: files
      dockerfile: Dockerfile
    volumes:
      - files:/files

volumes:
  files:
